name Update information data

on:
  schedule:
    - cron: "0 3 * * *"
    
  workflow_dispatch:

jobs:
  collect_info:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalacja bibliotek
        run: pip install -r requirements.txt

      - name: Aktualizacja danych informacyjnych
        run: python collect_info.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add database.db
          git commit -m "Aktualizacja danych informacyjnych" || echo "Brak zmian"
          git push