name: Test Python
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Zainstaluj zależności
        run: pip install -r requirements.txt

      - name: Uruchom program
        run: python collect.py